## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import ns3waf

def configure(conf):
    ns3waf.check_modules(conf, ['core', 'internet', 'point-to-point', 'netanim', 'csma'], mandatory = True)

def build(bld):
    bld.build_a_script('dce', needed = ['core', 'internet', 'dce', 'point-to-point', 'netanim', 'csma'],
				  target='bin/dce-iperf',
				  source=['dce-iperf.cc', 'misc-tools.cc']
				  )
